markdown: kramdown
permalink: pretty
future: true # do not hide future dates

collections:
  people:
    output: false
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  seminars:
    output: true
    permalink: /:collection/:path/
    
social:
  - title: bluesky
    url: https://bsky.app/profile/istaresearch.bsky.social
  - title: facebook
    url: https://www.facebook.com/ISTAustria
  - title: github
    url: http://github.com/istaustria
  - title: youtube
    url: https://www.youtube.com/user/ISTAustria


roles:
  - id: faculty
    title: Faculty
  - id: assistant
    title: Administrative Assistants
  - id: postdoc
    title: Senior Researchers
    short: Postdoc
  - id: phdstudent
    title: PhD Students
  - id: engineer
    title: Engineers
  - id: visitor
    title: Visitors
  - id: intern
    title: Interns
  - id: alumni
    title: Alumni

title: ISTA Visual Computing
url: https://istaustria.github.io
email: chafner@ist.ac.at
description: "ISTA Visual Computing"

## Fix use of this plugin
#plugins:
#  - jekyll-datapage-generator
#page_gen-dirs: true
#page-gen:
#- data: 'groups'
#  template: 'people'
#  name: 'grpid'
#  dir: 'people'